# Generated by Django 3.1.1 on 2020-12-10 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('dimension', models.CharField(choices=[('кг', 'кг'), ('г', 'г'), ('мл', 'мл'), ('л', 'л'), ('ч. л.', 'ч. л.'), ('ст. л.', 'ст. л.'), ('шт.', 'шт.'), ('по вкусу', 'по вкусу'), ('стакан', 'стакан'), ('батон', 'батон'), ('кусок', 'кусок'), ('бутылка', 'бутылка'), ('пакетик', 'пакетик'), ('пучок', 'пучок'), ('лист', 'лист')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_values', to='recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('cooking_time', models.PositiveSmallIntegerField(help_text='в минутах')),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(related_name='recipe_ing', through='recipes.IngredientValue', to='recipes.Ingredient')),
                ('tags', models.ManyToManyField(related_name='recipes_tag', to='recipes.Tag')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.AddField(
            model_name='ingredientvalue',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_values', to='recipes.recipe'),
        ),
    ]
